### ISSUE TITLE
Wireless connection

### ISSUE THREAD

**Issue by irooori** [nicosrm/24-emb-chess#8]
The Dezibot should be informed of its initial location via a wireless connection. This should be used to determine which figure is simulated. The move is then to be transmitted via the connection.

### Sub-tasks
- [ ] Decide whether to use WLAN or Bluetooth
- [ ] Establishing the connection
- [ ] Communication of initial field
- [ ] Communication of next move

**Comment by nicosrm** [comment]
Ansatzpunkt für BLE: https://randomnerdtutorials.com/esp32-bluetooth-low-energy-ble-arduino-ide/
